name: Deploy Notebook

on:
  push:
    branches:
      - main
      - dev
  repository_dispatch:
    types: [trigger-build-dev, trigger-build-latest]

jobs:
  call-parent-build:
    uses: msd-live/devops-common/.github/workflows/notebook-image-build.yml@main
